### ISSUE TITLE
OSError: [Errno 121] Remote I/O error

### ISSUE THREAD

**Issue by Kamalnl92** [pimoroni/mics6814-python#7]
Hello, 

I connected my sensor by mistake on 2,4,6,8,10 in place of 1,3,5,7,9. I placed it properly, now running gas.py I get the below error, I am not sure what the issue is now, is it hardware issue or software.

`Traceback (most recent call last):
  File "/home/pi5/Desktop/gas/mics6814-python/examples/gas.py", line 8, in <module>
    gas = MICS6814()
          ^^^^^^^^^^
  File "/home/pi5/.virtualenvs/pimoroni/lib/python3.11/site-packages/mics6814/__init__.py", line 43, in __init__
    self._ioe = io.IOE(i2c_addr, interrupt_timeout, interrupt_pin, gpio)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi5/.virtualenvs/pimoroni/lib/python3.11/site-packages/ioexpander/__init__.py", line 843, in __init__
    _IO.__init__(self, i2c_addr, interrupt_timeout, interrupt_pin, interrupt_pull_up, gpio, smbus_id, skip_chip_id_check, perform_reset)
  File "/home/pi5/.virtualenvs/pimoroni/lib/python3.11/site-packages/ioexpander/__init__.py", line 187, in __init__
    chip_id = self.get_chip_id()
              ^^^^^^^^^^^^^^^^^^
  File "/home/pi5/.virtualenvs/pimoroni/lib/python3.11/site-packages/ioexpander/__init__.py", line 460, in get_chip_id
    return self.i2c_read16(self.REG_CHIP_ID_L, self.REG_CHIP_ID_H)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi5/.virtualenvs/pimoroni/lib/python3.11/site-packages/ioexpander/__init__.py", line 231, in i2c_read16
    self._i2c_dev.i2c_rdwr(msg_w, msg_r)
  File "/usr/lib/python3/dist-packages/smbus2/smbus2.py", line 658, in i2c_rdwr
    ioctl(self.fd, I2C_RDWR, ioctl_data)
OSError: [Errno 121] Remote I/O error
`

Thank you!
Kamal

**Comment by Gadgetoid** [comment]
If you're talking physical pins then there's a non zero chance your sensor is toast!

You should try `sudo i2cdetect -y 1` and see if it shows up on 0x19, you might see something like:

```
       0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
  00:          -- -- -- -- -- -- -- -- -- -- -- -- --
  10: -- -- -- -- -- -- -- -- 19 -- -- -- -- -- -- --
  20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
  70: -- -- -- -- -- -- -- --
  ```

Note: you might need to `sudo apt install i2c-tools` for the above command.

**Comment by Kamalnl92** [comment]
I get 

```
0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- -- 
```

**Comment by helgibbons** [comment]
Closing this one for now, but let us know if you still need help.
